### ISSUE TITLE
Check whether rdf generation is still correctly working after multilanguage changes

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#100]
**Is your feature request related to a problem? Please describe.**
The rdf generation hasn't been checked since the addition of new columns to the ArtOntologyCrawler.py.

Create the art_ontology.rdf from art_ontology_en.json. Not from the csv files at the beginning (like it is done now).

**Why do you want this feature? What goals should be achieved**
Old features should still work after changes.

**Describe the solution you'd like**
Approval that the rdf generation still works or refactoring so that it works again.

**Describe acceptance criteria**
See above.

**Additional context**
The openartbrowser doesn't use the rdf file so this is probably not too urgent to fix

**Comment by BernhardHumm** [comment]
The RDF file should also contain all enriched information, including Wikipedia abstracts, video links etc. Insofar, RDF generation must be modified and placed in a different position of ETL, anyway.

 

           Bernhard Humm

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Dezember 2019 11:16
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Check whether rdf generation is still correctly working after multilanguage changes (#100)

 

Is your feature request related to a problem? Please describe.
The rdf generation hasn't been checked since the addition of new columns to the ArtOntologyCrawler.py.

Why do you want this feature? What goals should be achieved
Old features should still work after changes.

Describe the solution you'd like
Approval that the rdf generation still works or refactoring so that it works again.

Describe acceptance criteria
See above.

Additional context
The openartbrowser doesn't use the rdf file so this is probably not too urgent to fix

**Comment by tilomi** [comment]
Create the art_ontology.rdf from art_ontology_en.json. Not from the csv files at the beginning (like it is done now).

**Comment by wodjou** [comment]
In which branch could I best push the new python file to generate RDF-Data ? could I push that in to Multilanguage_backend?

**Comment by wodjou** [comment]
The RDF-Data is now generated from art_ontology_en.json.

**Comment by tilomi** [comment]
> In which branch could I best push the new python file to generate RDF-Data ? could I push that in to Multilanguage_backend?
Create a new branch for example "feature/100_generate_rdf" push and create a pull request from your new branch to staging
