### ISSUE TITLE
Python script add_videos not working on the server (but on a local machine)

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#101]
Locally i can execute on the server i get following error:
```stacktrace
Traceback (most recent call last):
  File "script_add_youtube_videos.py", line 70, in <module>
    add_youtube_videos()
  File "script_add_youtube_videos.py", line 44, in add_youtube_videos
    if check_links and not check_yt_id_valid(yt_id):
  File "script_add_youtube_videos.py", line 21, in check_yt_id_valid
    video_exists = (video["pageInfo"]["totalResults"] == 1)
KeyError: 'pageInfo'
```
I added debug prints and they are correct.

**Comment by lbucas** [comment]
I think I wrote an incorrect Except statement in the function. 

It should be:
`except (requests.HTTPError, KeyError):`

instead of 
`except requests.HTTPError or KeyError:`

**Comment by lbucas** [comment]
However, I do not know why the API response did not include _pageInfo_. It should be appear for both correct and broken video IDs.

**Comment by tilomi** [comment]
Yes the error is thrown after the request to the googleapi endpoint. However i do not know why this doesn't work on the server. I'll have to look it up some other time. If i print the created url and copy it into my browser it works.

**Comment by BernhardHumm** [comment]
As said before is the check on the server not important, since broken links are checked on the client.

 

           Bernhard Humm

 

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Dezember 2019 11:53
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Python script add_videos not working on the server (but on a local machine) (#101)

 

Yes the error is thrown after the request to the googleapi endpoint. However i do not know why this doesn't work on the server. I'll have to look it up some other time. If i print the created url and copy it into my browser it works.
