### ISSUE TITLE
Merge .gitignore files

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#115]
Currently there are two .gitignore files in the repository. 
Unless anyone from the backend team objects we can merge them and delete the one in the scripts directory

**Comment by mxxbe** [comment]
See https://github.com/hochschule-darmstadt/openartbrowser/pull/105#discussion_r354232358

**Comment by mxxbe** [comment]
#122

**Comment by tilomi** [comment]
For me it's fine. Maybe we should specify that in the wiki and readmes that we only want one gitignore.

**Comment by jschurse** [comment]
The solution in the feature branch is not equivalent. Now all *.json files in the project would be ignored, not only the ones in the /scripts/ dir.
We could either prefix all the rules in one .gitignore file on the base of the project, or keep our different .gitignore files that meet the different requirements of the corresponding parts of our projects.
I would prefer the second approach since backend and frontend use vastly different technology and close this issue.

Please reopen, if you would like to continue this discussion!

**Comment by jschurse** [comment]
Just for reference an equivalent file would need to look something like this:

```# IDEs / tooling
/.idea/
node_modules
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
.history/*


# Frontend
## profiling files
chrome-profiler-events.json
speed-measure-plugin.json

## compiled output
/app/dist
/app/tmp
/app/out-tsc
# Only exists if Bazel was run
/app/bazel-out

## misc
/app/.sass-cache
/app/connect.lock
/app/coverage
/app/libpeerconnection.log
/app/npm-debug.log
/app/yarn-error.log
/app/testem.log
/app/typings

# System Files
.DS_Store
Thumbs.db


#Backend
# Python
/scripts/__pycache__
/scripts/crawler_output
/scripts/*.pyc
/scripts/data_manipulation/google_dev_key.txt

apicache-py3
/scripts/*.ttl
/scripts/*.csv
/scripts/!languageconfig.csv
/scripts/!youtube_videos.csv
/scripts/*.json
/scripts/*.ctrl
/scripts/*.lwp
```
