### ISSUE TITLE
Slider swiping and general enhancement

### ISSUE THREAD

**Issue by JamieArmstrongArndt** [hochschule-darmstadt/openartbrowser#161]
**Is your feature request related to a problem? Please describe.**
The usage of the slider on mobile devices would be more easy to use if the slide changes could be also triggered by swiping. There is also a general lack of performance with the slider which could be reworked in the same step.

**Why do you want this feature? What goals should be achieved**
Make the UI more "natural" to use on mobile devices and with better performance in general.

**Describe the solution you'd like**
The current slide in the slider should be changed on the mouse down or a press action on a mobile device together with a swipe movement. 

**Describe acceptance criteria**
Integration of the sliding functionality to the ngb-carousel. 

**Describe alternatives you've considered**
Adding an alternative slider component i.e. [ngx-carousel](https://valor-software.com/ngx-bootstrap/#/carousel)

**What effects does your proposed solution have**
Possibly boost the performance of the carousel object and add the slider feature

**Comment by lbucas** [comment]
#57 might be related

**Comment by dernicolas** [comment]
Going to resolve this Issue when implementing a slider for videos

**Comment by dernicolas** [comment]
Did 1-2 days research into this topic. From my point of view the the slider should be completely refactored, because for silder improvement we would need an additional module what would also increase the complexity of the code. Moreover the code currently is not really understandable/ retraceable. There for this issue should be postponed to next semester.

**Comment by dernicolas** [comment]
#273 is the new issue for this.
