### ISSUE TITLE
The material abstract is shown on hover tooltip but not on the site of the material

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#216]
The material abstract is shown on hover tooltip but not on the site of the material. I'm not sure whether it should be displayed at all or the abstract is missing on the material site.
Example: https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q65661123 hover over sandstone you'll see the abstract of this material. If you go on the site of sandstone no abstract is displayed.

**Comment by jschurse** [comment]
I implemented it:
![image](https://user-images.githubusercontent.com/12964877/72076561-fc549780-32f5-11ea-9f02-acbd8836f2c3.png)
But these descriptions can become quite long with very specific (non art-related) information:
![image](https://user-images.githubusercontent.com/12964877/72076646-227a3780-32f6-11ea-88d7-5419b28670ae.png)

The same applies for motifs.

@BernhardHumm what do you think; should we add these abstracts to the material and motif pages?

**Comment by BernhardHumm** [comment]
The abstracts for the materials should NOT be displayed since they usually have no art-related information.

 

The abstracts for the motifs SHOULD be displayed so that the user can learn what is being depicted.

 

           Bernhard Humm

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. Januar 2020 15:42
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] The material abstract is shown on hover tooltip but not on the site of the material (#216)

 

I implemented it:
 <https://user-images.githubusercontent.com/12964877/72076561-fc549780-32f5-11ea-9f02-acbd8836f2c3.png> 
But these descriptions can become quite long with very specific (non art-related) information:
 <https://user-images.githubusercontent.com/12964877/72076646-227a3780-32f6-11ea-88d7-5419b28670ae.png> 

The same applies for motifs.

@BernhardHumm <https://github.com/BernhardHumm>  what do you think; should we add these abstracts to the material and motif pages?
