### ISSUE TITLE
New components artists, movements, locations, materials, genres, motifs

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/openartbrowser#296]
**Reason**
Currently there are pages presenting a concrete artist, movement, location etc., but no pages presenting ALL artists, movements, locations, materials, genres and motifs.

**Solution**
There shall be new components artists, movements, locations, materials, genres and motifs.
A concept needs to be deleloped first and discussed, before implementation can start. Open questions :
- How to get to these new pages? Frome the start page? From the search? From all other pages?
- Appearance of page? Dealing with large lists (scrawling)

**Alternatives**

**Effects**
More relevant information

**Acceptance criteria**

**Additional context**

**Comment by EeveesEyes** [comment]
I build a 'entities-component' which manages all of those pages in one component (no code duplication :) ). This component uses a new scrolling component, which fetches 20 items at a time.
Clicking one of the items takes the user to it's entity-page.

/movements :
![movements](https://user-images.githubusercontent.com/28682931/83354350-70044900-a358-11ea-88b2-fac9239ecd39.png)
/artists :
![artists](https://user-images.githubusercontent.com/28682931/83354493-5adbea00-a359-11ea-901b-e602cb44c1cb.png)

I linked the new pages right under the front-page carousels, because i didn't want to replace them.
![front-page](https://user-images.githubusercontent.com/28682931/83354351-71ce0c80-a358-11ea-8510-c9d42c680dea.png)

Scrolling 1500+ artworks works smooth on my machine. This didn't take long and is all open for discussion.

**Comment by BernhardHumm** [comment]
Very nice!

 

 

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Sonntag, 31. Mai 2020 16:14
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Author <author@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] New components artists, movements, locations, materials, genres, motifs (#296)

 

I build a 'entities-component' which manages all of those pages in one component (no code duplication :) ). This component uses a new scrolling component, which fetches 20 items at a time.
Clicking one of the items takes the user to it's entity-page.

/movements :
 <https://user-images.githubusercontent.com/28682931/83354350-70044900-a358-11ea-88b2-fac9239ecd39.png> 
/artists :
 <https://user-images.githubusercontent.com/28682931/83354493-5adbea00-a359-11ea-901b-e602cb44c1cb.png> 

I linked the new pages right under the front-page carousels, because i didn't want to replace them.
 <https://user-images.githubusercontent.com/28682931/83354351-71ce0c80-a358-11ea-8510-c9d42c680dea.png> 

Scrolling 1500+ artworks works smooth on my machine. This didn't take long and is all open for discussion.

**Comment by EeveesEyes** [comment]
TODO:
Add Title to each side: Artists, Movements ...
Add Link to badge on entity page, linking to entities page: Artist -> Artists
