### ISSUE TITLE
Create movements directional graph from wikidata dataset 

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#317]
**Reason**
Movements from wikidata come with several data-keys. In this case, these are the important ones:

- ~instance of~ [(P31)](https://www.wikidata.org/wiki/Property:P31) _this is pretty straight forward, we are looking for items which are instance of "art movement"_
- ~subclass of~ [(P279)](https://www.wikidata.org/wiki/Property:P279) _this is where the fun begins - "subclass of" is sometimes used instead of "part of". this means eg. "Early Renaissance" is not part of but subclass of "Renaissance" and the other way around with "Proto-Renaissance" [(fixed)](https://github.com/hochschule-darmstadt/openartbrowser/issues/138#issuecomment-620086673)_ 
- ~follows~ [(P155)](https://www.wikidata.org/wiki/Property:P155) _ideally this key contains the preceding movement (not always tho)_
- ~followed by~ [(P156)](https://www.wikidata.org/wiki/Property:P156)  _same story here_
- has part [(P527)](https://www.wikidata.org/wiki/Property:P527) _this key should contain all sub-movements (not always the case)_
- part of [(P361)](https://www.wikidata.org/wiki/Property:P361)  _sub-movements should have this key filled in_

This is a direct requirement of #69.

**Solution**
This needs to be discussed. Note that #288 is directly linked to this.
One solution for inconsistent data could be to alter/extend/fix the wikidata data-set
Furthermore these references need to be part of our dataset, so we know whether a movement is a main-movement or sub-movement and to display sub-movements on their main-movement-page.

**Alternatives**
Describe alternatives you've considered

**Effects**
What effects does your proposed solution have?

**Acceptance criteria**
Describe acceptance criteria for testing

**Additional context**

**Comment by BernhardHumm** [comment]
My suggestions:

1.       Use properties part_of and has_part only (check whether all entries in fact make sense)

2.       Regard has_part as inverse property of part_of

3.       Store in our art ontology part_of only.  For “A has_part B” add “B part_of A” to ontology (if not already existing).

4.       On client-side (Web app) display transitive closures for both directions: e.g. 
High Renaissance:
part of: Renaissance, …
contains: Italian High Renaissance, … 

5.       Transitive closures could (a) be computed as semantic enrichment during ETL or (b) live on client side (if performance is OK)

6.       Instance_of entries that actually mean part_of should be modified in Wikidata

7.       I would ignore the properties follows / followed_by. 
If it is meant chronologically, then the inception dates of the artworks will indicate this anyway. 
It it is meant in terms of influence, then the property influenced_by is already covered. 

 

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Montag, 27. April 2020 17:58
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Create movements directional graph from wikidata dataset (#317)

 

Reason
Movements from wikidata come with several data-keys. In this case, these are the important ones:

*	instance of (P31) <https://www.wikidata.org/wiki/Property:P31>  this is pretty straight forward, we are looking for items which are instance of "art movement"
*	subclass of (P279) <https://www.wikidata.org/wiki/Property:P279>  this is where the fun begins - "subclass of" is sometimes used instead of "part of". this means eg. "Early Renaissance" is not part of but subclass of "Renaissance" and the other way around with "Proto-Renaissance"
*	follows (P155) <https://www.wikidata.org/wiki/Property:P155>  ideally this key contains the preceding movement (not always tho)
*	followed by (P156) <https://www.wikidata.org/wiki/Property:P156>  same story here
*	has part (P527) <https://www.wikidata.org/wiki/Property:P527>  this key should contain all sub-movements (not always the case)
*	part of (P361) <https://www.wikidata.org/wiki/Property:P361>  sub-movements should have this key filled in

This is a direct requirement of #69 <https://github.com/hochschule-darmstadt/openartbrowser/issues/69> .

Solution
This needs to be discussed. Note that #288 <https://github.com/hochschule-darmstadt/openartbrowser/issues/288>  is directly linked to this.
One solution for inconsistent data could be to alter/extend/fix the wikidata data-set
Furthermore these references need to be part of our dataset, so we know whether a movement is a main-movement or sub-movement and to display sub-movements on their main-movement-page.

Alternatives
Describe alternatives you've considered

Effects
What effects does your proposed solution have?

Acceptance criteria
Describe acceptance criteria for testing

Additional context

**Comment by EeveesEyes** [comment]
As discussed, we need the following properties:
- instance of [(P31)](https://www.wikidata.org/wiki/Property:P31) _is already in the dataset_
and
- has part [(P527)](https://www.wikidata.org/wiki/Property:P527) _new_
- part of [(P361)](https://www.wikidata.org/wiki/Property:P361) _new_

**Comment by tilomi** [comment]
We created a PR for the new attributes. Has part and part of are loading all references (qids), this might be a problem later because not all references entities may be in our dataset. I would suggest to only allow values that are already within the movements that are referenced from the artworks, but we have to discuss this. Also the instance of is loaded in a classes file but not uploaded to elasticsearch at the moment we maybe have to change that too.

**Comment by BernhardHumm** [comment]
In the crawler you have to implement the loading of all movements that are in a transitive closure of has_part and part_of relationships.

This requires a recursive function. Similar functionality is implemented in loading all classes that are in a transitive subClassOf relationship. Have a look at the implementation there.

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Mai 2020 16:42
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Create movements directional graph from wikidata dataset (#317)

 

We created a PR for the new attributes. Has part and part of are loading all references (qids), this might be a problem later because not all references entities may be in our dataset. I would suggest to only allow values that are already within the movements that are referenced from the artworks, but we have to discuss this. Also the instance of is loaded in a classes file but not uploaded to elasticsearch at the moment we maybe have to change that too.

**Comment by tilomi** [comment]
We discussed today that we only want to allow movements that are already referenced from the artworks. Otherwise we maybe get wikidata items which are not referenced by artworks, are no art movements or are not related to art at all. This seems to be the easiest solution. If there is too less information we would try the transitive closure approach for the has_part and part_of attributes.
