### ISSUE TITLE
Use bulk insert instead of single insert for json docs when uploading to elasticsearch

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#339]
**Is your feature request related to a problem? Please describe.**
The crawling process was re-implemented and now uses directly the mediawiki-api for wikidata and wikipedia. Therefore the data extraction is much faster and the elasticsearch upload could also be improved by using the elasticsearch bulk-API. Currently the creation of 5 language dependend indices takes around 6 hours. With this change the whole process run even faster.

**Why do you want this feature? What goals should be achieved**
The elasticsearch upload is faster, it should at least be twice as fast (3 hours to insert everything).

**Describe the solution you'd like**
See above.

**Describe acceptance criteria**
See above.

**Describe alternatives you've considered**
Keep the current state because it just works.

**What effects does your proposed solution have**
Shorter ETL therefore better flexibility for changes regarding new properties from wikidata items.

**Comment by tilomi** [comment]
This was really easy to implement and i will merge it with the new data extraction. The time goes down from about 5 hours (1 for each index) to a few minutes for everything.

**Comment by BernhardHumm** [comment]
Great!

 

 

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Sonntag, 10. Mai 2020 14:10
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Use bulk insert instead of single insert for json docs when uploading to elasticsearch (#339)

 

This was really easy to implement and i will merge it with the new data extraction. The time goes down from about 5 hours (1 for each index) to a few minutes for everything.
