### ISSUE TITLE
Update documentation + refactoring for the new data extraction

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#341]
**Is your feature request related to a problem? Please describe.**
The whole data extraction was adjusted so the documentation needs to be updated.

**Why do you want this feature? What goals should be achieved**
Better maintainability

**Describe the solution you'd like**
Updated documentation

**Additional context**
To enable other teams to work faster on their new features for the openArtBrowser i would suggest this can be done later in the semester.

**Comment by BernhardHumm** [comment]
When you write the documentation later in the semester it will take longer because you have to remember how you did it.

So, why not doing it right now?

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Sonntag, 10. Mai 2020 15:09
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Documentation for new data extraction (#341)

 

Is your feature request related to a problem? Please describe.
The whole data extraction was adjusted so the documentation needs to be updated.

Why do you want this feature? What goals should be achieved
Better maintainability

Describe the solution you'd like
Updated documentation

Additional context
To enable other teams to work faster on their new features for the openArtBrowser i would suggest this can be done later in the semester.

**Comment by tilomi** [comment]
My idea was to first resolve loading new attributes and then write documentation and refactor so that we don't block other teams. Following issues have to be resolved #317 #298 #288 but i think this doesn't take too long and we can start at the very latest in 2 weeks with documentation which isn't too far away.

**Comment by BernhardHumm** [comment]
OK, great!

 

 

 

------------------------------------

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Montag, 11. Mai 2020 15:05
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Update documentation for new data extraction (#341)

 

My idea was to first resolve loading new attributes and then write documentation and refactor so that we don't block other teams. Following issues have to be resolved #317 <https://github.com/hochschule-darmstadt/openartbrowser/issues/317>  #298 <https://github.com/hochschule-darmstadt/openartbrowser/issues/298>  #288 <https://github.com/hochschule-darmstadt/openartbrowser/issues/288>  but i think this doesn't take too long and we can start at the very latest in 2 weeks with documentation which isn't too far away.
