### ISSUE TITLE
Add movement start and end time to movement page

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#420]
**Is your feature request related to a problem? Please describe.**
Currently the start and end time are used by some components but not displayed to the user. 

**Why do you want this feature? What goals should be achieved**
There is no reason not to display this. 

**Describe the solution you'd like**
One issue is the handling of estimated timestamps. I see several ways to do this:
1. display only start_time and end_time, ignore estimated timestamps 
>  This is quite easy and should be the minimum of what is done.
2. display them together, so the user cannot distinguish between estimated and crawled timestamps
>  is not transparent in any way and i think we should not do it 
3. display estimated and crawled timestamps separate from each other with a note/tool-tip what 'estimated' means/how we estimate these timestamps
> I would prefer this one, because it is a transparent way of informing the user, that these timestamps are not reliable / not proved but our own calculation. It does add some more complexity to the UI though. 

**Describe acceptance criteria**
Timestamps are displayed according to one of the solutions mentioned above. 
Example
> Start: 1850
Estimated End: 1933

or

> Period: 1850-1933

or something like this

Please add information which solution will be implemented.

**Comment by BernhardHumm** [comment]
I prefer alternative 1.

 

 

------------------------------------

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Juni 2020 10:12
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Add movement start and end time to movement page (#420)

 

Is your feature request related to a problem? Please describe.
Currently the start and end time are used by some components but not displayed to the user.

Why do you want this feature? What goals should be achieved
There is no reason not to display this.

Describe the solution you'd like
One issue is the handling of estimated timestamps. I see several ways to do this:

1.	display only start_time and end_time, ignore estimated timestamps

This is quite easy and should be the minimum of what is done.

2.	display them together, so the user cannot distinguish between estimated and crawled timestamps

is not transparent in any way and i think we should not do it

3.	display estimated and crawled timestamps separate from each other with a note/tool-tip what 'estimated' means/how we estimate these timestamps

I would prefer this one, because it is a transparent way of informing the user, that these timestamps are not reliable / not proved but our own calculation. It does add some more complexity to the UI though.

Describe acceptance criteria
Timestamps are displayed according to one of the solutions mentioned above.
Example

Start: 1850
Estimated End: 1933

or

Period: 1850-1933

or something like this

Please add information which solution will be implemented.
