### ISSUE TITLE
Artwork Display Bug

### ISSUE THREAD

**Issue by mxxbe** [hochschule-darmstadt/openartbrowser#430]
**Describe the bug**
Artwork display is broken, there are many JS errors on the console (see screenshot)

**To Reproduce**
- open https://openartbrowser.org/de/artwork/Q43485263 in your browser

**Expected behavior**
The page should behave like every other artwork page

**Screenshots**
![image](https://user-images.githubusercontent.com/22763390/86152090-f484eb80-baff-11ea-8514-42840729cd52.png)
![image](https://user-images.githubusercontent.com/22763390/86152141-036b9e00-bb00-11ea-9189-b0f206e28d28.png)

**Desktop (please complete the following information):**
 - OS: Windows 8, 10
 - Browser: Chrome, Firefox (here more content is displayed, but also not all of it)
 - Version: current Browser versions

**Additional context**
The bug might be closely related to iconclass.org returning `null` for the requested iconclass.

**Comment by mxxbe** [comment]
A guard for the iconclass component might already fix this issue for the frontend, but the underlying problem might also be, that we have iconclass values, that iconclass.org can not parse on their webservice - I suggest that both issues should be looked at when working on this.

**Comment by BernhardHumm** [comment]
There are more strange behaviours on this artwork: https://openartbrowser.org/de/artwork/Q43485263

 

1.       Empty mouse-over popup


2.       When clicking on this motif: 0 artworks   <https://openartbrowser.org/de/motif/Q18480509> https://openartbrowser.org/de/motif/Q18480509


 

 

 

 

------------------------------------

 

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Dienstag, 30. Juni 2020 19:20
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Artwork Display Bug (#430)

 

Describe the bug
Artwork display is broken, there are many JS errors on the console (see screenshot)

To Reproduce
Steps to reproduce the behavior:

*	open https://openartbrowser.org/de/artwork/Q43485263 in your browser

Expected behavior
The page should behave like every other artwork page

Screenshots
 <https://user-images.githubusercontent.com/22763390/86152090-f484eb80-baff-11ea-8514-42840729cd52.png> 
 <https://user-images.githubusercontent.com/22763390/86152141-036b9e00-bb00-11ea-9189-b0f206e28d28.png> 

Desktop (please complete the following information):

*	OS: Windows 8, 10
*	Browser: Chrome, Firefox (here more content is displayed, but also not all of it)
*	Version: current Browser versions

Additional context
The bug might be closely related to iconclass.org returning null for the requested iconclass.
