### ISSUE TITLE
Missing 'Iconography' translation

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#445]
**Describe the bug**
Attribute name 'Iconography' is not translated
-> Add translation
![tmp](https://user-images.githubusercontent.com/28682931/87029107-f6297000-c1df-11ea-8643-0e09a89e6b86.png)

**Comment by mxxbe** [comment]
Hmm, didn't you actually already [fix](this: https://github.com/hochschule-darmstadt/openartbrowser/pull/377/files) it a while ago?

**Comment by EeveesEyes** [comment]
You are right.. somehow this didn't work?

**Comment by mxxbe** [comment]
Ah I think I might have figured it out: we don't use `label` and the templating syntax, so the translations seem to be there but are not injected, since we still use the static label `Iconography:` instead of `{{ label }}:`. 
I will check if that's the issue, and might open a PR for this later this week :smile:
