### ISSUE TITLE
Show artworks without link resource

### ISSUE THREAD

**Issue by MadelineWall** [hochschule-darmstadt/openartbrowser#457]

**Comment by MadelineWall** [comment]
wrong github

**Comment by BernhardHumm** [comment]
This seems to be an error. The issue is for DDKArtBrowser, not for openArtBrowser

 

---

Viele Grüße

           Bernhard Humm

 

------------------------------------

Prof. Dr. Bernhard Humm

Geschäftsführender Direktor, Institut für angewandte Informatik Darmstadt (aiDa)

Vorsitzender Promotionsausschuss, Promotionszentrum Angewandte Informatik

h_da Hochschule Darmstadt - University of Applied Sciences, fbi Fachbereich Informatik 

Schöfferstr. 8b, D-64295 Darmstadt

Tel: +49 6151 16 38494, Fax: +49 6151 16 38935, Home Office: +49 6031 6714726

 <mailto:bernhard.humm@h-da.de> bernhard.humm@h-da.de, https://fbi.h-da.de/personen/bernhard-humm 

 

Von: MadelineWall <notifications@github.com> 
Gesendet: Donnerstag, 14. Januar 2021 12:37
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Show artworks without link resource (#457)

 

Reason (Why?)
Some artworks don't have recouses (pictures). But they have to show on the website.

Solution (What?)
A placeholder-image or placeholder-text will be show, if an artwork doesn't has a link resource

Out of scope

Relation to other Issues

Acceptance criteria
A placeholder instead of a picture.
