### ISSUE TITLE
Startpage carousel won't work without pictures

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#53]
CHECK WHETHER THIS BUG IS STILL OPEN, CLOSE OTHERWISE

I tried out the name refactoring on the ETL scripts for issue #21 . Our test data had only two movements in it and they both had no picture attribute:
- https://openartbrowser.org/movement/Q1404472 , https://www.wikidata.org/wiki/Q1404472
- https://openartbrowser.org/movement/Q1474884 , https://www.wikidata.org/wiki/Q1474884

This resulted in an empty carousel and also some errors on the angular frontend. I think this didn't occure until now because only movements with pictures were chosen for the carousel (?). 

I'm not sure how to handle this, maybe there could be an default picture for movements (or other subjects / topics) without an own image so that they can be discovered in the carousel.

Error's in this part of the application are very confusing when you want to test that the frontend can query the elasticsearch server.

**Comment by BernhardHumm** [comment]
Movements without image should not be displayed and simply disregarded. No default pictures.

(Similar logic is implemented for sliders when image links for artworks are broken. They are simply omitted)

 

 

           Bernhard Humm

 

--

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. November 2019 14:11
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Startpage carousel's won't work without pictures in movements (#53)

 

I tried out the name refactoring on the ETL scripts for issue #21 <https://github.com/hochschule-darmstadt/openartbrowser/issues/21>  . Our test data had only two movements in it and they both had no picture attribute:

*	https://openartbrowser.org/movement/Q1404472 , https://www.wikidata.org/wiki/Q1404472
*	https://openartbrowser.org/movement/Q1474884 , https://www.wikidata.org/wiki/Q1474884

This resulted in an empty carousel and also some errors on the angular frontend. I think this didn't occured until now because only movements with pictures were chosen for the carousel (?).

I'm not sure how to handle this, maybe there could be an default picture for movements (or other subjects / topics) without an own image so that they can be discovered in the carousel.

**Comment by tilomi** [comment]
I thought about it again. For testing i find it very confusing if parts of the page don't work because there is not enough data available. I think the best solution if there are not enough or no images for a category is probably logging this to console as a warning. The method in which this should be logged is in /app/src/pages/home/home.component.ts getCategoryItems
