### ISSUE TITLE
Display iconclass tag and link/display its meaning

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#58]
**Is your feature request related to a problem? Please describe.**
The Iconclass attribute is available in the wikidata dataset and is currently not used/displayed 

**Why do you want this feature? What goals should be achieved**
A user has a clear description what is depicted in the artwork. Furthermore a more professional user has a higher interest in our website.

**Describe the solution you'd like**
At least display the Iconclass tag and link the iconclass website. Furthermore the iconclass description could be displayed right beside it.
The wikidata field is named 'depicts Iconclass notation' and the content directly links to the Iconclass website.
Example: 
[depicts Iconclass notation](https://www.wikidata.org/wiki/Property:P1257): [61BB2(Lisa del Giocondo)11](http://iconclass.org/rkd/61BB2(Lisa%20del%20Giocondo)11/)
(From: [Wikidata Mona Lisa](https://www.wikidata.org/wiki/Q12418)  )
Additionally a way could be developed to teach the user a way to read the iconclass tag, like the [Iconclass](http://iconclass.org/rkd/61BB2(Lisa%20del%20Giocondo)11/#) Website is doing it.

**Describe acceptance criteria**
At least the Iconclass tag is displayed.

**Describe alternatives you've considered**
None

**What effects does your proposed solution have**
Better user experience, slight changes to the model.

**Additional context**
Example of the [Städel](https://sammlung.staedelmuseum.de/en/work/the-abdication-of-emperor-charles-v-in-favor-of-his-son-phil)'s usage
Example of the [Bildindex](https://www.bildindex.de/document/obj08012013?part=0&medium=bh012394)'s usage

**Comment by mauamy** [comment]
We could use a popup for the iconclass description and breakdown of the different parts.

**Comment by mxxbe** [comment]
Iconclass.org offers rdf or json iconclass data as a service if we add the correct extension to the url. See `http://iconclass.org/61BB2.json`.

Maybe we could add an additional page, that can display Artworks depicting the same iconclass notations (see `http://iconclass.org/61B.json` which depicts `"historical persons (portraits and scenes from the life)"`), since we already have, or can easily include all data we need for this.

A possible extension of this feature would be navigation through the linked data we get from Iconclass.org (for example to step "up" in the iconclass notation) and display more artworks that belong to the broader category (or left / right to display different categories - you get the idea).

**Comment by istthabel** [comment]
Created new branch and prepared new iconclass page. 'ng serve' compiles successfully. Page is not yet linked by any other pages.

**Comment by jschurse** [comment]
Should the user also be able to search for iconclass references via the searchbar?

**Comment by mxxbe** [comment]
We have to adapt the crawler around this position `https://github.com/hochschule-darmstadt/openartbrowser/blob/c019f8f716e11adb70a67a115cb126243ebdcf62/scripts/Wikidata%20crawler/ArtOntologyCrawler.py#L99` and include iconclasses - the frontend is already prepared.

**Comment by mxxbe** [comment]
Currently we will use the iconclass.org version to fetch iconclass descriptions; later we might implement RDF-to-JSON and use their dump in our ES.
In that case see [this](https://www.w3.org/TR/rdf-json/#h2_overview-of-rdf-json) for reference.

**Comment by BernhardHumm** [comment]
I think it is enough to display the Iconclass ID and label only (and not additionally the label of the top category, as discussed today). Makes it easier 

 

           Bernhard Humm

 

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Mittwoch, 27. November 2019 21:29
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Display iconclass tag and link/display its meaning (#58)

 

Iconclass.org offers rdf or json iconclass data as a service if we add the correct extension to the url. See http://iconclass.org/61BB2.json.

Maybe we could add an additional page, that can display Artworks depicting the same iconclass notations (see http://iconclass.org/61B.json which depicts "historical persons (portraits and scenes from the life)"), since we already have, or can easily include all data we need for this.

A possible extension of this feature would be navigation through the linked data we get from Iconclass.org (for example to step "up" in the iconclass notation) and display more artworks that belong to the broader category (or left / right to display different categories - you get the idea).

**Comment by mxxbe** [comment]
Working prototype implementation in #106
