### ISSUE TITLE
Add popup with abstract for tags

### ISSUE THREAD

**Issue by mauamy** [hochschule-darmstadt/openartbrowser#64]
**Is your feature request related to a problem? Please describe.**
Currently the user needs to click on a tag and change the page to retrieve more information on the related topic.

**Why do you want this feature? What goals should be achieved**
The user should be able to retrieve more information about the topics of the tags in a more convenient way. Thus the user should not need to click on a tag an change the actual page to retrieve more information.

**Describe the solution you'd like**
If you hover over a tag  popup should appear and show the corresponding Wikipedia abstract. If no abstract is available no popup should be shown.

**Describe acceptance criteria**
Every tag that has an corresponding abstract shows an popup containing this abstract when hovered over.

**Describe alternatives you've considered**
None

**What effects does your proposed solution have**
Frontend-wise this only should add a small amount of HTML. Because the needed data already provided the backend code should not be touched at all.

**Additional context**
![96a0513a7c4e45058531f2061a6d763a](https://user-images.githubusercontent.com/28682931/69333889-e281c700-0c59-11ea-8b7a-d9d4cdc0891c.png)

**Comment by JamieArmstrongArndt** [comment]
Hey there,

I have assigned this feature myself believing no one is working on this yet. At least it looks like it for now (no featuere branch open). 

Best regards,
Jamie

**Comment by JamieArmstrongArndt** [comment]
Hey @EeveesEyes and @mauamy,

so the current implementation looks like this:

![image](https://user-images.githubusercontent.com/22763537/70625885-aa9bed00-1c23-11ea-9cac-49ab453d4b17.png)

So what was not mentioned in the issue here, but what I already added, is the trimming of the length. Currently I am looking for the the next dot "." in the text after 150 characters. This works as long as there is no string like i.e. "Dr.". Is that enough for our use case for now? We could also add a sentence identification package which would add more overhead for such a simple issue, not sure if that makes sense, as long as this is the only use case of the package. What do you think? 

Apart from that the badge is a shared component with a pretty straight forward to use implementation, like seen here:
![image](https://user-images.githubusercontent.com/22763537/70626503-e1bece00-1c24-11ea-8e86-7aad89a15ff1.png)

Currently I only added it in the artist page, but if you give the green light for this solution, I would add it to the other pages.
